---
# ArcGIS Online Open Data item and query information
data_source:
  item_id:
  lyr_num:
  # List requested CVT codes below. Use quoted text (ex. 'J'). Remove all lines to request the entire dataset
  cvt_codes:
  - 'A_ex'
  - 'B_ex'

# WebGIS information
webgis:
  portal_url: https://gis.somemunicipality.com/portal
  username: SomeUser
  password: SomePassword
  # If the profile field is used - portal_url, username, and passwords fields are ignored
  profile: Profile_SomeGIS
  serv_folder:
  portal_item:

# GIS Environment settings
gis_env:
  workspace: C:/GIS/path/to/enterprise_geodatabase.sde/some_dataset
  overwrite_output: True
  out_fc_name: TaxParcel_SomeMunicipality
  # Projection Examples (match Esri's description):
  # NAD 1983 StatePlane Michigan South FIPS 2113 (Intl Feet)
  # WGS 1984 Web Mercator (auxiliary sphere)
  out_fc_proj: WGS 1984 Web Mercator (auxiliary sphere)

# Path to BS&A table export
csv_uri: C:/path/to/ExportedTable.CSV
...
