---
# Source WebGIS Information
source_gis:
  # If the profile field is used: url, username, and passwords fields are ignored
  # Leave url, username, password, and profile fields blank if connecting anonymously
  url:
  username:
  password:
  profile:
  item_id:
  lyr_num:

# Target WebGIS information
target_gis:
  # If the profile field is used: url, username, and passwords fields are ignored
  url: https://gis.targetmunicipality.com/portal
  username: TargetUser
  password: TargetPassword
  profile: Profile_TargetGIS
  item_id:
  lyr_num:
  # Target Feature Layer Projection
  projection: 2253
  # NAD 1983 StatePlane Michigan South FIPS 2113 (Intl Feet)
  # WGS 1984 Web Mercator (auxiliary sphere)

# List requested CVT codes below. Use quoted text (ex. 'J'). Remove all lines to request the entire dataset
cvt_codes:
  - 'ex_A'
  - 'ex_B'

# Path to BS&A table export
csv_uri: C:/path/to/ExportedTable.CSV
...
